'use client';
import {useState} from 'react';
import {track} from '@/lib/analytics';
import {tutors,slotsFor,BOOKING_KEY} from '@/lib/tutors';
export function DemoTools(){const [status,setStatus]=useState('Ready. Simulated traffic is labeled and does not reserve actual slots.');const [busy,setBusy]=useState(false);
 async function simulate(){setBusy(true);setStatus('Sending representative journeys…');let accepted=0;let sent=0;
 for(let i=0;i<6;i++){const tutor=tutors[i];const distinct=`abc-simulation-${crypto.randomUUID()}`;const props={simulated:true,tutor_id:tutor.id,tutor_name:tutor.name,subject:tutor.subjects[0],grade:tutor.grades[0],session_format:i%2?'in-person':'online',selected_time:slotsFor(tutor)[0],device_type:i<4?'Mobile':'Desktop'};
 const events=['$pageview','tutor_browse','tutor_filter','tutor_profile_view','booking_started','time_slot_selected','session_format_selected',...(i===1?[]:['booking_request_completed'])];
 for(const event of events){sent++;if(await track(event,{...props,page:event==='$pageview'?'/':'/tutors',subjects:tutor.subjects,grade_levels:tutor.grades.map(String)},distinct))accepted++;}}
 setStatus(`${accepted} of ${sent} events accepted by the ingestion endpoint.\nExpected demo: 6 visitors, 5 requests, all 3 subjects, both formats, 4 mobile and 2 desktop visitors.\nVerify processing in PostHog Activity before interpreting results.`);setBusy(false);}
 return <><p className="eyebrow">Prototype demonstration</p><h1 className="booking-title">Demo tools</h1><p className="lead">Generate labeled traffic or restore this browser’s sample availability.</p><div className="demo-actions"><button className="button button-primary" disabled={busy} onClick={()=>void simulate()}>Generate sample traffic</button><button className="button button-secondary" disabled={busy} onClick={()=>{if(window.confirm('Remove all demo booking requests from this browser and restore availability?')){try{localStorage.removeItem(BOOKING_KEY);window.dispatchEvent(new Event('abc-bookings'));setStatus('Demo requests removed. All future sample times are available again.');}catch{setStatus('Browser storage is unavailable.');}}}}>Reset demo bookings</button></div><output className="demo-status" aria-live="polite">{status}</output><p className="muted">This is a public prototype utility, not an admin dashboard. No contact details or booking totals are shown.</p></>;}
