'use client';
import {useEffect,useState} from 'react';
import {tutors,gradeLabel,gradeRange,scheduleLabel,available,slotLabel,type Tutor} from '@/lib/tutors';
import {track} from '@/lib/analytics';
import {NativeSelect} from '@/components/ui/native-select';

export function TutorPhoto({tutor}:{tutor:Tutor}){return <img className="tutor-photo" src={`https://i.pravatar.cc/400?img=${tutor.photo}`} alt={`Placeholder portrait for sample tutor ${tutor.name}`} width={400} height={400} loading="lazy"/>;}
export function TutorDirectory(){
 const [subject,setSubject]=useState('');const [grade,setGrade]=useState('');const [day,setDay]=useState('');const [rate,setRate]=useState('55');const [selected,setSelected]=useState<Tutor|null>(null);const [slots,setSlots]=useState<Record<string,string[]>>({});const [error,setError]=useState('');
 useEffect(()=>{function update(){try{setSlots(Object.fromEntries(tutors.map(t=>[t.id,available(t)])));}catch{setError('Browser storage is unavailable. Enable it to view and request times.');}}update();window.addEventListener('storage',update);window.addEventListener('abc-bookings',update);void track('tutor_browse',{page:'/tutors'});return()=>{window.removeEventListener('storage',update);window.removeEventListener('abc-bookings',update);};},[]);
 function filter(field:string,value:string){const next={subject,grade,availability:day,max_rate:rate,[field]:value};void track('tutor_filter',next);if(field==='subject')setSubject(value);if(field==='grade')setGrade(value);if(field==='availability')setDay(value);if(field==='max_rate')setRate(value);}
 function view(t:Tutor){setSelected(t);void track('tutor_profile_view',{tutor_id:t.id,tutor_name:t.name,subjects:t.subjects,grade_levels:t.grades.map(String)});window.scrollTo({top:0,behavior:'smooth'});}
 const filtered=tutors.filter(t=>(!subject||t.subjects.includes(subject))&&(!grade||t.grades.includes(Number(grade)))&&t.rate<=Number(rate)&&(!day||(slots[t.id]||[]).some(s=>day==='weekend'?[0,6].includes(new Date(s).getDay()):![0,6].includes(new Date(s).getDay()))));
 if(selected)return <><button className="text-link" onClick={()=>setSelected(null)}>← Back to all tutors</button><div className="detail-grid"><div><TutorPhoto tutor={selected}/><p className="muted">Placeholder photo · not an actual ABC tutor</p></div><section><span className="sample-badge">Sample profile</span><h1 className="detail-title">{selected.name}</h1><p className="lead">{selected.subjects.join(' & ')} · Grades {gradeRange(selected)}</p><p className="rate">${selected.rate}<span> / one-hour session</span></p><p>Weekly: {scheduleLabel(selected)}</p><p className="muted">Online or in person. We’ll coordinate the platform or location after your request.</p><h2 className="small-heading">Available times</h2><p className="muted">Next four weeks · times in your device’s timezone</p>{error&&<p role="alert">{error}</p>}<div className="slot-grid">{(slots[selected.id]||[]).slice(0,12).map(s=><a className="slot" key={s} href={`/booking?tutor=${selected.id}&slot=${encodeURIComponent(s)}`} onClick={()=>void track('time_slot_selected',{tutor_id:selected.id,selected_time:s})}>{slotLabel(s)}</a>)}</div>{!error&&slots[selected.id]?.length===0&&<p>No times available in the next four weeks. Try another tutor.</p>}<a className="button button-primary" href={`/booking?tutor=${selected.id}`}>Request a session</a></section></div></>;
 return <><header className="directory-heading"><div><p className="eyebrow">A little support. A lot of possibility.</p><h1>Find your tutor</h1><p className="lead">Personal support in math, science, and reading.<br/>Choose the right fit for your student.</p></div><p className="sample-note">Meet our six sample tutors.<br/>All profiles, photos, and schedules are placeholders.</p></header><div className="filter-bar"><label>Subject<NativeSelect value={subject} onChange={e=>filter('subject',e.target.value)}><option value="">All subjects</option>{['Math','Science','Reading'].map(s=><option key={s}>{s}</option>)}</NativeSelect></label><label>Student grade<NativeSelect value={grade} onChange={e=>filter('grade',e.target.value)}><option value="">All grades</option>{Array.from({length:13},(_,i)=><option key={i} value={i}>{gradeLabel(i)}</option>)}</NativeSelect></label><label>Availability<NativeSelect value={day} onChange={e=>filter('availability',e.target.value)}><option value="">Any day</option><option value="weekday">Weekdays</option><option value="weekend">Weekends</option></NativeSelect></label><label>Hourly rate<NativeSelect value={rate} onChange={e=>filter('max_rate',e.target.value)}>{[40,45,50,55].map(r=><option key={r} value={r}>Up to ${r}</option>)}</NativeSelect></label></div><div className="results-line"><p aria-live="polite">{filtered.length} {filtered.length===1?'tutor':'tutors'} to explore</p><button className="text-link" onClick={()=>{setSubject('');setGrade('');setDay('');setRate('55');void track('tutor_filter',{subject:'',grade:'',availability:'',max_rate:'55'});}}>Clear filters</button></div>{error&&<p role="alert">{error}</p>}<div className="tutor-grid">{filtered.map(t=><article className="tutor-card" key={t.id}><div className="portrait-wrap"><TutorPhoto tutor={t}/><span className="sample-badge">Sample profile</span></div><div className="tutor-card-body"><div className="card-title"><h2>{t.name}</h2><p className="rate">${t.rate}<span>/hr</span></p></div><div className="subject-tags">{t.subjects.map(s=><span key={s}>{s}</span>)}</div><p>Grades {gradeRange(t)} · One-hour sessions</p><p className="muted">{scheduleLabel(t)}</p><p className="next-slot">{slots[t.id]?.[0]?`Next: ${slotLabel(slots[t.id][0])}`:'View available times'}</p><button className="button button-secondary full-width" onClick={()=>view(t)}>View profile & times <span aria-hidden="true">↗</span></button></div></article>)}</div>{filtered.length===0&&<section className="foundation-panel"><h2>Let’s try a wider search</h2><p>Adjust a filter to see more tutors.</p></section>}</>;
}
